# Generated by Django 3.1.1 on 2020-09-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0004_auto_20200924_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(null=True, upload_to='posts_images'),
        ),
    ]
