# Generated by Django 3.1.1 on 2020-09-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0005_post_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Insta.post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Insta.user')),
            ],
        ),
    ]
