# Generated by Django 3.1.1 on 2020-09-25 07:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Insta', '0007_auto_20200925_1246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Likes',
        ),
    ]
