# Generated by Django 3.1.1 on 2020-09-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0009_auto_20200925_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
